### ISSUE TITLE
It doesn't update in all items in a flat grid or flat item in a scroll view, this happens in android only.

### ISSUE THREAD

**Issue by kaleeswarish** [cawfree/react-native-custom-fonts#2]
I am getting the following error for items that are not currently visible in a flat list.

Possible Unhandled Promise Rejection (id: 0):
Error: Failed to findViewById using handle 0x32f.
Error: Failed to findViewById using handle 0x32f.
    at createErrorFromErrorData (/Users/parkal/Documents/StutiSadhanam-Client/.vscode/.react/index.bundle:2114:17)
    at /Users/parkal/Documents/StutiSadhanam-Client/.vscode/.react/index.bundle:2066:27
    at MessageQueue.__invokeCallback (/Users/parkal/Documents/StutiSadhanam-Client/.vscode/.react/index.bundle:2633:18)
    at /Users/parkal/Documents/StutiSadhanam-Client/.vscode/.react/index.bundle:2364:18
    at MessageQueue.__guard (/Users/parkal/Documents/StutiSadhanam-Client/.vscode/.react/index.bundle:2537:13)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (/Users/parkal/Documents/StutiSadhanam-Client/.vscode/.react/index.bundle:2363:14)
    at /Users/parkal/Documents/StutiSadhanam-Client/.vscode/.react/debuggerWorker.js:187:58
    at process.<anonymous> (/Users/parkal/Documents/StutiSadhanam-Client/.vscode/.react/debuggerWorker.js:60:9)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)

**Comment by cawfree** [comment]
Likely because the views have been unmounted whilst offscreen. Would it be possible to try remounting the component when fonts have been changed?
